name: release-binary
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: pyinstaller ./SwitchPokePilot.spec --noconfirm

      - name: Zip binary
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist/SwitchPokePilot-Windows.zip dist/SwitchPokePilot.exe

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: SwitchPokePilot-Windows.zip
          path: dist/SwitchPokePilot-Windows.zip

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build
        run: pyinstaller ./SwitchPokePilot.spec --noconfirm

      - name: Zip binary
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dist/SwitchPokePilot-macOS.zip dist/SwitchPokePilot.app

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: SwitchPokePilot-macOS.zip
          path: dist/SwitchPokePilot-macOS.zip

  release:
    needs: [ build-windows, build-macos ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows
        uses: actions/download-artifact@v3
        with:
          name: SwitchPokePilot-Windows.zip

      - name: Download macOS
        uses: actions/download-artifact@v3
        with:
          name: SwitchPokePilot-macOS.zip

      - name: Release binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SwitchPokePilot-Windows.zip
            SwitchPokePilot-macOS.zip
